{
 "title": "iDRAC Exporter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource1", "label": "Datasource1", "query": "prometheus" },
   {
    "name": "resource",
    "query": {
     "query": "label_values(idrac_memory_module_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$resource iDRAC BIOS Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idrac_system_bios_info{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$resource RAM Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "idrac_system_memory_size_bytes{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$resource Machine Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "idrac_system_machine_info{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$resource CPU Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "idrac_system_cpu_count{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$resource Indicator Light",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idrac_system_indicator_led_on{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$resource System Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idrac_system_health{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "$resource Fan Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "repeat": "resource",
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "idrac_sensors_fan_speed{job=\"$resource\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$resource Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "idrac_sensors_temperature{job=\"$resource\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "$resource Consumed Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "idrac_power_control_consumed_watts{job=\"$resource\"}"
    }
   ]
  },
  { "title": "Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "$resource Drive Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_drive_capacity_bytes{job=\"$resource\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "$resource Disk Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "idrac_drive_info{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "$resource Memory Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_memory_module_speed_mhz{job=\"$resource\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "$resource Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_memory_module_capacity_bytes{job=\"$resource\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "$resource Memory Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "idrac_memory_module_health{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "$resource Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "idrac_sel_entry{job=\"$resource\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}