{{- if and (not .Values.existingSecret) .Values.idracConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idrac-exporter.fullname" . }}-config
  labels:
    {{- include "idrac-exporter.labels" . | nindent 4 }}
stringData:
  idrac.yml: {{ tpl .Values.idracConfig . | quote }}
{{- end }}
